name: Docker
on:
  push:
  schedule:
    - cron: "30 3 * * *"

jobs:
  docker-bake:
    if: github.ref_name != 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get latest Tailscale version
        id: tailscale-latest
        run: >
          VERSION=$(
            curl -s https://api.github.com/repos/tailscale/tailscale/releases |
            jq -r '.[0].tag_name'
          ) && echo "VERSION=${VERSION#v*}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/bake-action@v2
        env:
          TS_VERSION: ${{ steps.tailscale-latest.outputs.VERSION }}
        with:
          pull: true
          targets: release
